<a href="https://colab.research.google.com/github/sasan-osmannezhad/test/blob/main/peceptron_sklearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Perceptron simple calasifiction applied on iris_flower data set.

In [ ]:
import numpy as np
from sklearn.linear_model import Perceptron
from sklearn.datasets import load_iris

In [ ]:
iris_data = load_iris()
iris_data

In [ ]:
X= iris_data["data"]
y = iris_data.target
# y = y==0
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
perceptron = Perceptron()

In [ ]:
perceptron.fit(X,y)

Perceptron()

In [ ]:
perceptron.score(X,y)

0.48

In [ ]:
X.shape

(150, 4)

In [ ]:
perceptron.coef_

array([[  1.9,   6. ,  -8.8,  -3.9],
       [ 18.7, -27.6,  11.2, -24.1],
       [-37.4, -29.2,  52.6,  54.5]])

In [ ]:
perceptron.intercept_

array([  1.,  16., -22.])